### ISSUE TITLE
build: commit c06f8ad09 on main does not compile, breaking git bisect across the #1247 series

### ISSUE THREAD

**Issue by newhoggy** [rust-works/succinctly#1626]
**Severity: Low** (no runtime impact; costs bisect time)

## Summary

Commit `c06f8ad09` ("fix(jq, yaml, test): close the keys/keys_unsorted decode gap
(#1247)") on `main` does not compile. It made `effective_keys` fallible and left two
CLI call sites in `src/bin/succinctly/jq_runner.rs` unadapted; the very next commit,
`c2136af61`, fixes them as an aside ("Also routes the CLI-side `keys`/`keys_unsorted`
materializing-fallback call sites through the newly-fallible `effective_keys` from the
preceding commit").

Found while trying to A/B `c2136af61` against its parent to price that commit in
isolation — the baseline build failed.

## Repro

```console
$ git checkout --detach c06f8ad09
$ cargo build --release --features cli,simd
error[E0599]: no method named `sort` found for enum `Result<T, E>` in the current scope
    --> src/bin/succinctly/jq_runner.rs:2980:22
error[E0631]: type mismatch in function arguments
    --> src/bin/succinctly/jq_runner.rs:2983:38
error[E0599]: the method `collect` exists for struct `Map<IntoIter<Vec<String>>, ...>`,
              but its trait bounds were not satisfied
    --> src/bin/succinctly/jq_runner.rs:2983:58
... the same three again at :3129 / :3131 ...
error: could not compile `succinctly` (bin "succinctly") due to 9 previous errors
```

Verified on x86_64 Linux. Any build that includes the CLI binary is affected; the
errors are all in `jq_runner.rs`.

## Why it matters

`git bisect` across this point fails to build rather than answering, so anyone bisecting
a `jq`/CLI regression through the #1247 range has to notice the failure is unrelated and
`git bisect skip` it. That is exactly the moment when a stray build error is most
expensive, because the natural reading is "the bug is here".

## Why CI did not catch it

CI builds the PR head and the merge result, not each commit in the series. Nothing in
the current workflow compiles intermediate commits.

## Options

1. **Do nothing but record it.** `main` is public; fixing the commit itself means
   rewriting history. This issue then exists so a future bisector finds the explanation.
2. **Add a per-commit build check** to CI for PRs above some commit count — catches the
   class, but costs CI minutes on every stacked PR.
3. **Note it in the contributing/rebase guidance** — a stacked series should be
   `git rebase --exec 'cargo check --features cli'` before pushing, which is cheap and
   catches exactly this.

(3) is the cheapest real fix and needs no CI change. Filing rather than choosing.

**Comment by newhoggy** [comment]
🔧 Claimed by agent `Elmo` — branch `issue-1626-stacked-commit-bisectability`

Going with option 3 from the issue body — adding `git rebase --exec 'cargo check --features cli'` guidance to CONTRIBUTING.md, since the issue itself calls it out as the cheapest real fix requiring no CI change and rewriting main's history is off the table for a public repo (option 1).
