### ISSUE TITLE
yq: $__loc__ (and unbound $vars generally) diverge from real yq's silent-empty-output behavior

### ISSUE THREAD

**Issue by newhoggy** [rust-works/succinctly#2776]
## Summary

Surfaced during #2688's code review (three independent reviewer passes
converged on this live-oracle finding, cross-checking against Homebrew
`yq` v4.53.3, the project's pinned yq oracle).

`Expr::Loc` (`$__loc__`)'s evaluation in `src/jq/eval.rs`'s `eval_single` is
mode-generic (no `S: EvalSemantics` branch) -- it runs identically for both
`succinctly jq` and `succinctly yq`. But real yq does not implement
`$__loc__` as a builtin at all:

```console
$ echo '{}' | yq '$__loc__'
$ echo $?
0
```

Empty stdout, exit 0. `--verbose` shows real yq parses `$__loc__` as
`GET_VARIABLE __loc__` -- an ordinary, *unbound* variable reference -- and
silently drops the whole expression's output ("no matching results, nothing
to print"). This isn't `$__loc__`-specific: **any** unbound variable behaves
the same way in real yq:

```console
$ echo '{}' | yq '$foo'
$ echo $?
0
```

`succinctly yq` diverges on both counts:

```console
$ echo '{}' | succinctly yq '$__loc__'
{"file": "<top-level>", "line": 1}
$ echo '{}' | succinctly yq '$foo'
Error: undefined variable: $foo
```

## Why this is separate from #2688

This is a **pre-existing** divergence, not introduced by #2688 -- yq mode
already emitted a `$__loc__` object before that PR (with the old,
also-wrong `"<stdin>"` string); #2688 only changed which incorrect literal
was inside the still-incorrect object. Fixing it properly means deciding
and implementing general unbound-variable semantics for `succinctly yq`
(silently drop output, matching real yq's own quirky behavior, per
ADR-0018's bug-for-bug-fidelity default) -- a much wider change than a
`$__loc__`-specific tweak, since it touches how *any* unbound `$var`
resolves in yq mode, not just this one pseudo-variable.

## Also missing

Per `CLAUDE.md`'s fidelity rule ("every divergence must be recorded"),
neither `docs/compliance/yq/limitations.md` nor
`docs/reference/yq-language.md`'s "Gated jq Builtins (--jq-extensions)"
list currently mentions `$__loc__` or general unbound-variable handling at
all -- this divergence has been silently unrecorded until now.

## Suggested next step

1. Decide the target behavior for yq mode: either (a) reproduce real yq's
   bug-for-bug "unbound variable silently drops output" behavior generally
   (the ADR-0018-preferred default), or (b) gate `$__loc__` specifically
   behind `--jq-extensions` like the rest of the jq-only builtin surface
   real yq's lexer rejects (`leaf_paths`, `paths`, `limit`, etc. -- though
   note `$__loc__` currently parses in `ParserMode::Yq` today with no gate,
   unlike those).
2. Whichever is chosen, add the missing `docs/compliance/yq/limitations.md`
   entry (and `yq-language.md`'s gated-builtins list, if (b)).
