### ISSUE TITLE
x86_64: detect_fast_bmi2 calls __cpuid outside unsafe, breaking builds on Rust < 1.96

### ISSUE THREAD

**Issue by maxiboch** [rust-works/succinctly#474]
`detect_fast_bmi2()` in `src/util/simd/x86.rs` is a **safe** `fn` that calls `core::arch::x86_64::__cpuid` without an `unsafe` block:

```rust
#[cfg(all(target_arch = "x86_64", any(feature = "std", test)))]
fn detect_fast_bmi2() -> bool {
    ...
    let cpuid0 = core::arch::x86_64::__cpuid(0);
    ...
    let cpuid1 = core::arch::x86_64::__cpuid(1);
```

That compiles only on toolchains where `__cpuid` is a safe intrinsic. On Rust 1.93.0 it is a hard error:

```
error[E0133]: call to unsafe function `__cpuid` is unsafe and requires unsafe function or block
   --> src/util/simd/x86.rs:191:18
    |
191 |     let cpuid0 = core::arch::x86_64::__cpuid(0);
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior

error: could not compile `succinctly` (lib) due to 2 previous errors
```

Reproduced at rev `190da06d1b1c6611e3aba7246ef3a2a11f6edb72` building for `x86_64-pc-windows-msvc` with the `regex` feature on Rust 1.93.0. Both `__cpuid` call sites are affected. The same code path applies to `x86_64-unknown-linux-gnu`.

## Why it may not show up in your CI

The whole module is `target_arch = "x86_64"` gated, so any aarch64 build (Apple Silicon, ARM Linux) never compiles it. We only found it when a CI job ran on x86_64 for the first time in months — every other lane in our fleet is ARM64.

## Impact

This makes Rust 1.96 the *de facto* MSRV for x86_64 consumers, without that being declared anywhere. Consumers on an older pinned toolchain fail to build on x86_64 while building fine on aarch64, which is a confusing failure to diagnose — the error points at a dependency, not at the toolchain pin.

## Suggested fix

Wrap the two calls, since the surrounding fn is safe and the calls are genuinely unsafe operations:

```rust
let cpuid0 = unsafe { core::arch::x86_64::__cpuid(0) };
let cpuid1 = unsafe { core::arch::x86_64::__cpuid(1) };
```

`__cpuid` has no target-feature precondition on `x86_64` (CPUID is baseline), so the safety obligation is trivially met and an `// SAFETY:` note to that effect would document it. This keeps the crate buildable on older toolchains as well as new ones.

Happy to send a PR if useful.
